generate:
  - types
  - client
accessModifier: public
namingStrategy: idiomatic
typeOverrides:
  schemas:
    InvoiceView: InvoiceViewFilter
    CreditNoteView: CreditNoteViewFilter
    UserPermissionLevel: PermissionLevel